### ISSUE TITLE
MSVC Debug build 3.0a3 can't find zlib.lib

### ISSUE THREAD

**Issue by yoerg** [modelon-community/fmi-library#108]
Building 3.0a3 as a MSVC project with

    cmake -G "Visual Studio 16 2019" "../fmi-library-3.0a2"
    cmake --build . --config Debug

failes to link _fmizip.lib_ and aborts the build:

    fmizip.vcxproj -> C:\Hubele\scm\faster-bitbucket\fmi-library-build\buildMSVC30a3\Debug\fmizip.lib
    LINK : fatal error LNK1104: cannot open file 'zlibext\Debug\zlib.lib' [C:\Hubele\scm\faster-bitbuck
    et\fmi-library-build\buildMSVC30a3\compress_test_fmu_zip.vcxproj]

The reason appears to be that the _zlib_ Debug configuration build produces a _zlib**d**.lib_ instead of _zlib.lib_. I've attached a [crude workaround](https://github.com/modelon-community/fmi-library/files/13613119/msvc-debug-build-3.0a3.patch).

cmake version 3.26.4

**Comment by nilotpalutkalit** [comment]
Another workaround is to use find_package for zlib by enabling "FMILIB_FIND_PACKAGE_ZLIB" in CMAKE Options

**Comment by modelonrobinandersson** [comment]
Thank you both for your suggestions, I'll see if we can resolve this by next week.
