### ISSUE TITLE
co-simulation

### ISSUE THREAD

**Issue by YanceyYq** [modelon-community/fmi-library#120]
Is it supported to perform co-simulation on two FMU files? How can it be achieved?

**Comment by PeterMeisrimelModelon** [comment]
This is bit out-of-scope of FMILibrary, but you may want to check out [PyFMI](https://github.com/modelon-community/PyFMI), which is for the simulation of FMUs. There, you might be interested in the [Master](https://github.com/modelon-community/PyFMI/blob/master/src/pyfmi/master.pyx) algorithm.

/Peter

**Comment by YanceyYq** [comment]
Thank you for your answer.
