### ISSUE TITLE
library built no fmi2Instantiate.

### ISSUE THREAD

**Issue by YanceyYq** [modelon-community/fmi-library#125]
environment
ubuntu
fmi-library=fmi-library-3.0a3
cmake = 3.22.1
Compile fmi-library-3.0a3 using CMake
library built from source code. When using the nm command to view it, there is no fmi2Instantiate.
![error](https://github.com/modelon-community/fmi-library/assets/14902988/f6055964-9afd-4ef2-9eb3-a722b4632278)

**Comment by modelonrobinandersson** [comment]
Hi @YanceyYq I think you misunderstood my reply at https://github.com/modelon-community/PyFMI/issues/240.
The issue is in the FMU generation, neither PyFMI nor FMI Library generates an FMU. The results you show in your picture above is expected.

**Comment by YanceyYq** [comment]
Thank you for your answer.
