### ISSUE TITLE
AddressSanitizer reports several memory leaks

### ISSUE THREAD

**Issue by jorhk** [modelon-community/fmi-library#13]
Building the library tests with `-fsanitize=leak -fsanitize=address` shows several leaks, e.g.

    Direct leak of 144 byte(s) in 1 object(s) allocated from:
        #0 0x7faffeb07040 in calloc (/usr/lib/x86_64-linux-gnu/libasan.so.3+0xc7040)
        #1 0x7faffe7c4455 in fmi1_import_allocate (~/fmi-library-2.3/build/libfmilib_shared.so+0xe455)

[Log file with full output](https://github.com/modelon-community/fmi-library/files/6862620/ctest.log). We also encounter these leaks when we call _fmi-library_ in our project.

I've tested fmi-library-2.3 with these commands on ubuntu-focal:

    cmake ~/fmi-library-2.3 '-DCMAKE_CXX_FLAGS=-O1 -g -fsanitize=address -fsanitize=leak -fno-omit-frame-pointer' '-DCMAKE_EXE_LINKER_FLAGS=-fsanitize=address -fsanitize=leak' '-DCMAKE_SHARED_LINKER_FLAGS=-O -fsanitize=address -fsanitize=leak'
    make install
    ctest --verbose

**Comment by filip-stenstrom** [comment]
Release 2.4 has fixed memory leaks for Enum parsing in the library code, and other leaks that were only local to the tests.

We're using Memcheck via Valgrind to verify that no tests have memory leaks. (There are some issues reported for tests that use external tools, e.g. `ctest_build_all` and `ctest_fmi1_logger_test_check` but that's not related to code in this project.)

If you still see memory leaks, please re-open.
