### ISSUE TITLE
Loading the Instantiate function for all 3 types of execution mode (ME, CS & SE) as common functions.

### ISSUE THREAD

**Issue by KishorBasavaraju-NI** [modelon-community/fmi-library#148]
Irrespective of simulation mode, instantiation functions for all the simulation kind are loaded as the common functions in [fmi3_capi_load_common_fcn()](https://github.com/modelon-community/fmi-library/blob/f2f2a7be01777d37b8da047f501cc9d6b9e759a7/src/CAPI/src/FMI3/fmi3_capi.c#L63C1-L65C43).

If I have a FMU built for Co-Simulation and doesn't have entry point for `fmi3InstantiateModelExchange` and `fmi3InstantiateScheduledExecution`, then fmi3_import_create_dllfmu fails with an error. This behavior mandates the FMU to have all the 3 instantiation function entry points irrespective of the simulation mode.

Kindly fix this!

**Comment by filip-stenstrom** [comment]
This was changed in FMI 3.0.1: https://github.com/modelica/fmi-standard/pull/1868
