### ISSUE TITLE
jm_log_level_to_string double define when include fmilib.h and fmi_zip_zip.h

### ISSUE THREAD

**Issue by aoxipo** [modelon-community/fmi-library#17]
Hello! i'm try to use the Fmi-Library to process FMU files, but i meet the error like 
`jm_log_level_to_string has been define in fmilib_shared.lib(fmilib_shared.dll)`
when i use the `#include <fmilib.h>` and `#include <FMI/fmi_zip_zip.h>` at same time,
here is my code
![2021-11-18 203531](https://user-images.githubusercontent.com/32930325/142416362-fd9c1917-517a-44cc-82cf-37a19e880189.png)
i am tryed to use it with out the `jm_log_level_to_string` but program just crashed. 
Do you have any good solution suggestions? Am I using this correctly?

**Comment by filip-stenstrom** [comment]
From what I can see fmi_zip_zip.h is not part of FMILs public interface so in a client application you should not include it. You should only include the header files that are in <install>/include.

**Comment by aoxipo** [comment]
Think you for your help，you are right 。 i should not to include fmi_zip_zip, it's my problem.what ever think you again.
