### ISSUE TITLE
Warnings treated as errors when compiling with warning level 4

### ISSUE THREAD

**Issue by cekef** [modelon-community/fmi-library#20]
With version 2.4 from fmi-library, there are warnings treated as errors when compiling with cmake warning level4:

include\JM\jm_callbacks.h(209): warning C4100: 'include\JM\jm_callbacks.h(209): error C2220: the following warning is treated as an error
include\JM\jm_callbacks.h(209): error C2220: the following warning is treated as an error
include\JM\jm_callbacks.h(209): warning C4100: 'fmt': unreferenced formal parameter
include\JM\jm_callbacks.h(209): warning C4100: 'module': unreferenced formal parameter
include\JM\jm_callbacks.h(209): warning C4100: 'cb': unreferenced formal parameter
include\JM\jm_callbacks.h(214): warning C4100: 'fmt': unreferenced formal parameter
include\JM\jm_callbacks.h(214): warning C4100: 'module': unreferenced formal parameter
include\JM\jm_callbacks.h(214): warning C4100: 'cb': unreferenced formal parameter
include\JM\jm_callbacks.h(99): warning C4505: 'jm_get_last_error': unreferenced local function has been removed
include\JM\jm_callbacks.h(104): warning C4505: 'jm_clear_last_error': unreferenced local function has been removed
include\JM\jm_callbacks.h(209): warning C4505: 'jm_log_debug_v': unreferenced local function has been removed
include\JM\jm_callbacks.h(214): warning C4505: 'jm_log_debug': unreferenced local function has been removed
include\FMI1\fmi1_types.h(48): warning C4505: 'fmi1_get_platform': unreferenced local function has been removed
include\FMI2\fmi2_types.h(53): warning C4505: 'fmi2_get_types_platform': unreferenced local function has been removed

**Comment by filip-stenstrom** [comment]
Thanks for reporting, we're aware of this. (By default it builds with /W3 on MSVC where this is not an issue.)
