### ISSUE TITLE
Error parsing 'independent' variable

### ISSUE THREAD

**Issue by hplatou** [modelon-community/fmi-library#21]
If modelDescription.xml (FMI2) contains a variable with causality=independent, the xml-parser reports a parse error:
`[error  ] [FMI Library: FMI2XML] Start attribute is required for this causality, variability and initial combination`

According to the specification, this variable must be defined without the start attribute:
`If one variable is defined as "independent", it must be defined as
"Real" without a "start" attribute.`

**Comment by lionelbelmon** [comment]
Hi, we noticed the same problem here. 
One other way to solve it is to modify the table in fmi_enum.c
https://github.com/modelon-community/fmi-library/pull/98

**Comment by PeterMeisrimelModelon** [comment]
Has been fixed in https://github.com/modelon-community/fmi-library/pull/129
