### ISSUE TITLE
Unable to compile fmilib_shared

### ISSUE THREAD

**Issue by simonegenovese** [modelon-community/fmi-library#27]
Dear support to Build PyFMI project in Win64 it requires the fmilib_shared.lib library:
`LINK : fatal error LNK1181: cannot open input file 'fmilib_shared.lib'`

But when I build the fmi-library I'm not able to generate such static file.
Here the command I'm using.
`cmake -DFMILIB_BUILDING_LIBRARY=ON -DFMILIB_BUILD_SHARED_LIB=OFF -DFMILIB_BUILD_STATIC_LIB=ON -DFMILIB_BUILD_FOR_SHARED_LIBS=OFF -DFMILIB_BUILD_TESTS=OFF -G "MinGW Makefiles" E:\ESTECO\FMI\fmi-library`

Can you suggest me the correct way?
Thanks

**Comment by filip-stenstrom** [comment]
Sorry for the delay in response.

`fmilib_shared.lib` is the import library for the shared library. You will only get it with exactly that name if you build with MSVC. If you build with MinGW you'll get `fmilib_shared.dll.a`. In either case you would need `-DFMILIB_BUILD_SHARED_LIB=ON`.

**Comment by filip-stenstrom** [comment]
(Closing since this is old and probably resolved by now.)
