### ISSUE TITLE
Export fmi2_import_alloc_variable_list function

### ISSUE THREAD

**Issue by hyumo** [modelon-community/fmi-library#3]
It is found that `FMILIB_EXPORT` prefix is missing for `fmi2_import_alloc_variable_list` function. 
https://github.com/modelon-community/fmi-library/blob/0bf8a2e1aea1cc76010b7fb5f2a5fb4fb2da0e9e/src/Import/include/FMI2/fmi2_import_variable_list.h#L46

Greatly appreciated if this could be added. Thanks.

**Comment by filip-stenstrom** [comment]
Fixed in 80cfd8df6cfacfbb9f296f27fb8d64ecb1d11c61
