### ISSUE TITLE
Bad fmi2_import_get_default_experiment_step() default return value

### ISSUE THREAD

**Issue by kyllingstad** [modelon-community/fmi-library#4]
If `fmiModelDescription.xml` does not contain an `fmiModelDescription.DefaultExperiment.stepSize` attribute, `fmi2_import_get_default_experiment_step()` returns a default value of `1e-2`.

I see a few problems with this:
* This behaviour is not documented in the API reference, nor does it seem to be specified in the FMI 2.0 standard.
* `1e-2` seems like a rather arbitrary choice, and for a lot of FMUs, it does not make sense at all.
* Client code has no way of knowing whether a return value of `1e-2` comes from the FMU model description or is just the FMI Library default.

A simple fix would be to return zero or some other special value which is not a valid step size, and to document this.

By the way, other `fmiX_import_get_Y()` functions may have the same issue; this is just the one I ran across.

**Comment by filip-stenstrom** [comment]
The same problem exists for getting DefaultExperiment's tolerance. The current plan is to extend the API with something like:

FMILIB_EXPORT int fmi2_import_default_experiment_tolerance_exists(...)

The same approach will then probably have to taken for the other default_experiment functions that return "default" values.

**Comment by kyllingstad** [comment]
I'm glad to hear that you have a plan for it.

Even with a function like `fmi2_import_default_experiment_step_exists()`, I'd recommend strongly against returning a default step size of `1e-2` from `fmi2_import_get_default_experiment_step()`. If it returns zero – or even better, NaN – it'll be easier for developers to spot when they've forgotten to call `_exists()`. In addition, the simulations are more likely to fail fast rather than going on producing inaccurate or wrong results.

**Comment by filip-stenstrom** [comment]
Added new API (both fmi1 and fmi2):
FMILIB_EXPORT int fmi2_import_get_default_experiment_has_start(fmi2_import_t* fmu);
FMILIB_EXPORT int fmi2_import_get_default_experiment_has_stop(fmi2_import_t* fmu);
FMILIB_EXPORT int fmi2_import_get_default_experiment_has_tolerance(fmi2_import_t* fmu);
FMILIB_EXPORT int fmi2_import_get_default_experiment_has_step(fmi2_import_t* fmu);

The old default values still exist, but a warning will be logged if they (the default values) are accessed.
