### ISSUE TITLE
SVR to FMU

### ISSUE THREAD

**Issue by litz92** [modelon-community/fmi-library#75]
Helloo... I am very new to python + AI model.

Recently I make a prediction model with SVR, and I would like to apply this to Star CCM+(simulation tool) so that I can do co-simulation.

I have read modules explanation, but I couldn't find how to export python prediction model to FMU...

IF you know the solution, please help me. 

FYI : Star ccm+ supports FMU 1.0 /2.0

**Comment by PeterMeisrimelModelon** [comment]
I am afraid fmi-library won't be able to help with your issue, since it is a pure **import** tool for FMUs.
